### ISSUE TITLE
Thrall's Shadow

### ISSUE THREAD

**Issue by DavidTheMaaster** [SoftCactusTeam/Warcraft-Heroes-Beyond-Time#45]
* Build: 0.3

* Type: Art

* Description: The shadow of Thrall changes the color depending on the animation

* Severity:
  - [ ] Critical
  - [ ] Major
  - [x] Minor

* Priority:
  - [ ] Urgent
  - [ ] High
  - [ ] Normal
  - [x] Low

* Steps to reproduce:

* Frequency:

**Comment by nintervik** [comment]
Fixed spritsheet! :)
