### ISSUE TITLE
Player direction

### ISSUE THREAD

**Issue by DavidTheMaaster** [SoftCactusTeam/Warcraft-Heroes-Beyond-Time#46]
* Build: 0.3

* Type: Controller

* Description: If you change fast the direction of the gamepad stick, the player keeps movieng the the previous direction

* Severity:
  - [ ] Critical
  - [x] Major
  - [ ] Minor

* Priority:
  - [ ] Urgent
  - [x] High
  - [ ] Normal
  - [ ] Low

* Steps to reproduce: Change fast the direction on the gamepad 

* Frequency: Always

**Comment by nintervik** [comment]
With free movement this has been fixed
