### ISSUE TITLE
Portal appears in player position

### ISSUE THREAD

**Issue by nintervik** [SoftCactusTeam/Warcraft-Heroes-Beyond-Time#65]
* Build: v0.8.2.3

* Type: Code

* Description: the portal appears just under the player and you're teleported into the boss room without even seen the portal.

* Severity:
  - [ ] Critical
  - [ ] Major
  - [X] Minor

* Priority:
  - [ ] Urgent
  - [ ] High
  - [ ] Normal
  - [X] Low

* Steps to reproduce: just play the game and kill all the archers or press 9 to directly spawn the portal.

* Frequency: Jus happened to me one time. The chances of happening are very low.

**Comment by DatBeQuiet** [comment]
PEW
