### ISSUE TITLE
Feedback from a random guy

### ISSUE THREAD

**Issue by CapitanLiteral** [SoftCactusTeam/Warcraft-Heroes-Beyond-Time#75]
* Build: Warcraft Heroes Beyond Time v0.3.2

* Type: Feedback

Abro este issue para deciros que lo que lleváis hecho en esta build esta muy chulo. Muchos animos!

**Comment by nintervik** [comment]
Muchas gracias por los ánimos! :)

**Comment by morgadoCV** [comment]
thanks buddy!

**Comment by DavidTheMaaster** [comment]
Se aprecian los animos después de las charlas de Ricard
