### ISSUE TITLE
Portal sound fx plays multiple times

### ISSUE THREAD

**Issue by nintervik** [SoftCactusTeam/Warcraft-Heroes-Beyond-Time#77]
* Build: v03.3

* Type: audio and code

* Description: portal sound fx plays multiple times when entering into boss room.

* Severity:
  - [ ] Critical
  - [ ] Major
  - [X] Minor

* Priority:
  - [ ] Urgent
  - [ ] High
  - [ ] Normal
  - [X] Low

* Steps to reproduce: hit F1 to enter to boss room.

* Frequency: almost always.

**Comment by Jony635** [comment]
F1 Dont check if key down was pressed
